"""
SENTINEL Elite - CI/CD Integration

Integrates SENTINEL into development workflows:
- GitHub Actions workflow generation
- Pre-commit hooks
- GitLab CI support
- Slack/Discord alerts
- PR comments with findings
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from enum import Enum
import json
import yaml


class CIProvider(Enum):
    GITHUB_ACTIONS = "github_actions"
    GITLAB_CI = "gitlab_ci"
    CIRCLE_CI = "circle_ci"
    JENKINS = "jenkins"


class AlertChannel(Enum):
    SLACK = "slack"
    DISCORD = "discord"
    TELEGRAM = "telegram"
    EMAIL = "email"
    WEBHOOK = "webhook"


@dataclass
class CIConfig:
    """CI/CD configuration"""
    provider: CIProvider
    trigger_on: List[str] = field(default_factory=lambda: ["push", "pull_request"])
    branches: List[str] = field(default_factory=lambda: ["main", "develop"])
    fail_on_severity: str = "HIGH"  # HIGH, MEDIUM, LOW, INFO
    auto_comment_pr: bool = True
    alert_channels: List[AlertChannel] = field(default_factory=list)
    custom_rules_path: Optional[str] = None
    exclude_paths: List[str] = field(default_factory=list)


class GitHubActionsGenerator:
    """Generate GitHub Actions workflow for SENTINEL"""

    WORKFLOW_TEMPLATE = """
name: SENTINEL Security Audit

on:
  push:
    branches: {branches}
    paths:
      - '**.sol'
      - '**.vy'
      - '**.rs'
      - '**.move'
  pull_request:
    branches: {branches}
    paths:
      - '**.sol'
      - '**.vy'
      - '**.rs'
      - '**.move'
  workflow_dispatch:
    inputs:
      full_audit:
        description: 'Run full audit (slower but more thorough)'
        required: false
        default: 'false'
        type: boolean

concurrency:
  group: sentinel-${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

jobs:
  sentinel-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install SENTINEL
        run: |
          pip install sentinel-audit
          # Or install from source
          # pip install -e .

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run SENTINEL Audit
        id: audit
        env:
          OPENAI_API_KEY: ${{{{ secrets.OPENAI_API_KEY }}}}
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
        run: |
          sentinel audit . \\
            --output-format sarif \\
            --output-file sentinel-results.sarif \\
            --severity-threshold {severity_threshold} \\
            {extra_flags}

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: sentinel-results.sarif

      - name: Comment on PR
        if: github.event_name == 'pull_request' && steps.audit.outputs.findings_count > 0
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('sentinel-results.json', 'utf8'));

            let comment = '## 🛡️ SENTINEL Security Audit Results\\n\\n';

            if (results.critical > 0) {{
              comment += `❌ **${{results.critical}} Critical Issues Found**\\n\\n`;
            }}
            if (results.high > 0) {{
              comment += `⚠️ **${{results.high}} High Severity Issues**\\n\\n`;
            }}

            comment += '### Summary\\n';
            comment += `| Severity | Count |\\n`;
            comment += `|----------|-------|\\n`;
            comment += `| Critical | ${{results.critical}} |\\n`;
            comment += `| High | ${{results.high}} |\\n`;
            comment += `| Medium | ${{results.medium}} |\\n`;
            comment += `| Low | ${{results.low}} |\\n`;

            comment += '\\n---\\n';
            comment += '_Generated by [SENTINEL](https://github.com/sentinel-audit)_';

            github.rest.issues.createComment({{
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            }});

      - name: Fail on critical findings
        if: steps.audit.outputs.critical_count > 0
        run: |
          echo "Critical vulnerabilities found!"
          exit 1
"""

    def generate(self, config: CIConfig) -> str:
        """Generate GitHub Actions workflow"""

        branches_yaml = json.dumps(config.branches)
        severity_map = {"CRITICAL": "critical", "HIGH": "high", "MEDIUM": "medium", "LOW": "low"}
        severity = severity_map.get(config.fail_on_severity, "high")

        extra_flags = []
        if config.exclude_paths:
            for path in config.exclude_paths:
                extra_flags.append(f"--exclude {path}")
        if config.custom_rules_path:
            extra_flags.append(f"--rules {config.custom_rules_path}")

        return self.WORKFLOW_TEMPLATE.format(
            branches=branches_yaml,
            severity_threshold=severity,
            extra_flags=" \\\n            ".join(extra_flags) if extra_flags else ""
        )


class PreCommitHookGenerator:
    """Generate pre-commit hooks for SENTINEL"""

    HOOK_CONFIG = """
# SENTINEL Security Pre-commit Hook
# Add this to your .pre-commit-config.yaml

repos:
  - repo: local
    hooks:
      - id: sentinel-quick-scan
        name: SENTINEL Quick Security Scan
        entry: sentinel scan --quick
        language: system
        types: [solidity]
        pass_filenames: true
        always_run: false

      - id: sentinel-full-audit
        name: SENTINEL Full Audit
        entry: sentinel audit
        language: system
        types: [solidity]
        pass_filenames: true
        stages: [manual]  # Only run with: pre-commit run --hook-stage manual sentinel-full-audit

  # Alternative: Use slither as quick check
  - repo: https://github.com/crytic/slither
    rev: 0.10.0
    hooks:
      - id: slither
        entry: slither
        args: ['--exclude', 'naming-convention,external-function']
"""

    BASH_HOOK = """#!/bin/bash
# SENTINEL pre-commit hook
# Copy to .git/hooks/pre-commit and chmod +x

set -e

echo "🛡️ Running SENTINEL security scan..."

# Get staged .sol files
STAGED_SOL=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.sol$' || true)

if [ -z "$STAGED_SOL" ]; then
    echo "No Solidity files staged, skipping SENTINEL scan"
    exit 0
fi

# Run quick scan on staged files
sentinel scan --quick $STAGED_SOL

# Check exit code
if [ $? -ne 0 ]; then
    echo ""
    echo "❌ SENTINEL found security issues!"
    echo "Please fix the issues before committing."
    echo ""
    echo "To bypass (not recommended): git commit --no-verify"
    exit 1
fi

echo "✅ SENTINEL scan passed"
exit 0
"""

    def generate_yaml(self) -> str:
        """Generate pre-commit config YAML"""
        return self.HOOK_CONFIG

    def generate_bash_hook(self) -> str:
        """Generate bash pre-commit hook"""
        return self.BASH_HOOK


class GitLabCIGenerator:
    """Generate GitLab CI configuration"""

    GITLAB_CI = """
# SENTINEL Security Audit for GitLab CI
# Add to .gitlab-ci.yml

stages:
  - security

variables:
  SENTINEL_SEVERITY_THRESHOLD: "{severity_threshold}"

sentinel-audit:
  stage: security
  image: python:3.11-slim
  before_script:
    - pip install sentinel-audit slither-analyzer
    - curl -L https://foundry.paradigm.xyz | bash
    - foundryup
  script:
    - sentinel audit . --output-format gitlab --severity-threshold $SENTINEL_SEVERITY_THRESHOLD
  artifacts:
    reports:
      sast: sentinel-gl-sast-report.json
    paths:
      - sentinel-report.json
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "**/*.sol"
        - "**/*.vy"
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - "**/*.sol"
        - "**/*.vy"

sentinel-quick:
  stage: security
  image: python:3.11-slim
  before_script:
    - pip install sentinel-audit
  script:
    - sentinel scan --quick .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "**/*.sol"
"""

    def generate(self, config: CIConfig) -> str:
        severity_map = {"CRITICAL": "critical", "HIGH": "high", "MEDIUM": "medium", "LOW": "low"}
        return self.GITLAB_CI.format(
            severity_threshold=severity_map.get(config.fail_on_severity, "high")
        )


class AlertNotifier:
    """Send security alerts to various channels"""

    SLACK_TEMPLATE = {
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "🛡️ SENTINEL Security Alert"
                }
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": "*Repository:*\n{repo}"},
                    {"type": "mrkdwn", "text": "*Branch:*\n{branch}"}
                ]
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*Findings Summary:*\n• Critical: {critical}\n• High: {high}\n• Medium: {medium}\n• Low: {low}"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*Top Issues:*\n{top_issues}"
                }
            },
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "View Full Report"},
                        "url": "{report_url}"
                    }
                ]
            }
        ]
    }

    DISCORD_TEMPLATE = {
        "embeds": [
            {
                "title": "🛡️ SENTINEL Security Alert",
                "color": 15158332,  # Red
                "fields": [
                    {"name": "Repository", "value": "{repo}", "inline": True},
                    {"name": "Branch", "value": "{branch}", "inline": True},
                    {"name": "Critical", "value": "{critical}", "inline": True},
                    {"name": "High", "value": "{high}", "inline": True},
                    {"name": "Medium", "value": "{medium}", "inline": True},
                    {"name": "Low", "value": "{low}", "inline": True}
                ],
                "description": "**Top Issues:**\n{top_issues}",
                "footer": {"text": "Generated by SENTINEL"}
            }
        ]
    }

    def format_slack_alert(self, findings: Dict[str, Any]) -> Dict:
        """Format findings for Slack"""
        top_issues = "\n".join([
            f"• [{f['severity']}] {f['title']}"
            for f in findings.get("issues", [])[:5]
        ])

        message = json.loads(json.dumps(self.SLACK_TEMPLATE))

        # Replace placeholders
        message_str = json.dumps(message)
        message_str = message_str.replace("{repo}", findings.get("repo", "unknown"))
        message_str = message_str.replace("{branch}", findings.get("branch", "unknown"))
        message_str = message_str.replace("{critical}", str(findings.get("critical", 0)))
        message_str = message_str.replace("{high}", str(findings.get("high", 0)))
        message_str = message_str.replace("{medium}", str(findings.get("medium", 0)))
        message_str = message_str.replace("{low}", str(findings.get("low", 0)))
        message_str = message_str.replace("{top_issues}", top_issues)
        message_str = message_str.replace("{report_url}", findings.get("report_url", "#"))

        return json.loads(message_str)

    def format_discord_alert(self, findings: Dict[str, Any]) -> Dict:
        """Format findings for Discord"""
        top_issues = "\n".join([
            f"• [{f['severity']}] {f['title']}"
            for f in findings.get("issues", [])[:5]
        ])

        message = json.loads(json.dumps(self.DISCORD_TEMPLATE))
        message_str = json.dumps(message)
        message_str = message_str.replace("{repo}", findings.get("repo", "unknown"))
        message_str = message_str.replace("{branch}", findings.get("branch", "unknown"))
        message_str = message_str.replace("{critical}", str(findings.get("critical", 0)))
        message_str = message_str.replace("{high}", str(findings.get("high", 0)))
        message_str = message_str.replace("{medium}", str(findings.get("medium", 0)))
        message_str = message_str.replace("{low}", str(findings.get("low", 0)))
        message_str = message_str.replace("{top_issues}", top_issues)

        return json.loads(message_str)


class SARIFGenerator:
    """Generate SARIF format for GitHub Security tab"""

    def generate(self, findings: List[Dict[str, Any]]) -> Dict:
        """Generate SARIF output"""

        severity_map = {
            "CRITICAL": "error",
            "HIGH": "error",
            "MEDIUM": "warning",
            "LOW": "note",
            "INFO": "none"
        }

        rules = []
        results = []

        for i, finding in enumerate(findings):
            rule_id = f"SENTINEL-{i:04d}"

            rules.append({
                "id": rule_id,
                "name": finding.get("type", "unknown"),
                "shortDescription": {"text": finding.get("title", "Security Issue")},
                "fullDescription": {"text": finding.get("description", "")},
                "defaultConfiguration": {
                    "level": severity_map.get(finding.get("severity", "MEDIUM"), "warning")
                },
                "properties": {
                    "tags": ["security", "smart-contract"],
                    "precision": "high"
                }
            })

            results.append({
                "ruleId": rule_id,
                "level": severity_map.get(finding.get("severity", "MEDIUM"), "warning"),
                "message": {"text": finding.get("description", "")},
                "locations": [
                    {
                        "physicalLocation": {
                            "artifactLocation": {
                                "uri": finding.get("file", "unknown.sol")
                            },
                            "region": {
                                "startLine": finding.get("line", 1)
                            }
                        }
                    }
                ]
            })

        return {
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": [
                {
                    "tool": {
                        "driver": {
                            "name": "SENTINEL",
                            "version": "1.0.0",
                            "informationUri": "https://github.com/sentinel-audit",
                            "rules": rules
                        }
                    },
                    "results": results
                }
            ]
        }


class CIIntegrationManager:
    """Manage CI/CD integrations"""

    def __init__(self):
        self.github_gen = GitHubActionsGenerator()
        self.precommit_gen = PreCommitHookGenerator()
        self.gitlab_gen = GitLabCIGenerator()
        self.notifier = AlertNotifier()
        self.sarif_gen = SARIFGenerator()

    def generate_ci_config(self, config: CIConfig) -> str:
        """Generate CI configuration for the specified provider"""

        if config.provider == CIProvider.GITHUB_ACTIONS:
            return self.github_gen.generate(config)
        elif config.provider == CIProvider.GITLAB_CI:
            return self.gitlab_gen.generate(config)
        else:
            raise ValueError(f"Unsupported CI provider: {config.provider}")

    def generate_precommit_config(self) -> Dict[str, str]:
        """Generate pre-commit hook configurations"""
        return {
            ".pre-commit-config.yaml": self.precommit_gen.generate_yaml(),
            ".git/hooks/pre-commit": self.precommit_gen.generate_bash_hook()
        }

    def format_alert(self, channel: AlertChannel, findings: Dict[str, Any]) -> Dict:
        """Format alert for specified channel"""

        if channel == AlertChannel.SLACK:
            return self.notifier.format_slack_alert(findings)
        elif channel == AlertChannel.DISCORD:
            return self.notifier.format_discord_alert(findings)
        else:
            return findings

    def generate_sarif(self, findings: List[Dict[str, Any]]) -> Dict:
        """Generate SARIF report"""
        return self.sarif_gen.generate(findings)


# Convenience functions
def generate_github_workflow(
    branches: List[str] = None,
    fail_on: str = "HIGH"
) -> str:
    """Generate GitHub Actions workflow"""
    config = CIConfig(
        provider=CIProvider.GITHUB_ACTIONS,
        branches=branches or ["main", "develop"],
        fail_on_severity=fail_on
    )
    manager = CIIntegrationManager()
    return manager.generate_ci_config(config)


def generate_precommit_hooks() -> Dict[str, str]:
    """Generate pre-commit hooks"""
    manager = CIIntegrationManager()
    return manager.generate_precommit_config()


def generate_sarif_report(findings: List[Dict]) -> Dict:
    """Generate SARIF report from findings"""
    manager = CIIntegrationManager()
    return manager.generate_sarif(findings)
