"""
Free orientation report: runs every LLM-free Sentinel phase against a target
and emits a single markdown document that primes a human auditor for manual
hunting. Zero API cost.

Pulls together:
  - Phase 0.5 audit-intel (prior-audit known findings + post-audit priority files)
  - Pre-bounty git enumeration (fix-shaped PRs, open issues)
  - Solana scanner: entrypoints, PDA derivations, CPI calls, unchecked arith,
    unwraps, init_if_needed, realloc, cfg_if variant asymmetry
  - File size sort (Path 3 small-file-speed strategy)

Usage:
    python scripts/free_orient.py <target-path> [--out <file.md>]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("target", type=Path, help="Path to the codebase")
    p.add_argument("--out", type=Path, default=None,
                   help="Output markdown path (default: <target>/free-orient.md)")
    args = p.parse_args()

    target = args.target.resolve()
    if not target.exists():
        print(f"target not found: {target}", file=sys.stderr)
        return 1

    out_path = args.out or (target / "free-orient.md")
    lines: list[str] = []

    # --- Phase 0.5: Audit Intel ---
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from src.core.audit_intel import load_audit_intel

    audit_dir, known_findings, priority_files = load_audit_intel(target)

    lines.append(f"# Free Orientation Report: {target.name}")
    lines.append("")
    lines.append(f"Target: `{target}`")
    lines.append("")
    lines.append("Generated by Sentinel free_orient (zero LLM cost).")
    lines.append("Use this as the starting checklist for manual hunting.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # --- Known findings to AVOID ---
    lines.append(f"## Known findings to skip ({len(known_findings)})")
    lines.append("")
    if not known_findings:
        lines.append("_No prior audits or fix-shaped PRs detected. The whole "
                     "surface is fair game._")
    else:
        lines.append("These have ALREADY been documented or fixed. "
                     "Re-reporting any of these wastes your time.")
        lines.append("")
        for kf in known_findings:
            sev = f" [{kf.severity}]" if kf.severity else ""
            status = f" ({kf.status})" if kf.status else ""
            src = f" — {kf.source}" if kf.source else ""
            lines.append(f"- **{kf.id}**{sev}{status}: {kf.title}{src}")
    lines.append("")

    # --- Priority files (highest EV) ---
    lines.append(f"## Priority files: post-audit changes ({len(priority_files)})")
    lines.append("")
    if not priority_files:
        lines.append("_No post-audit-changed files detected (or not a git "
                     "repository / shallow clone)._")
    else:
        lines.append("Files modified AFTER the latest audit was added to git. "
                     "Auditors have NOT seen this surface. Read these first.")
        lines.append("")
        for pf in priority_files[:50]:
            lines.append(f"- `{pf}`")
        if len(priority_files) > 50:
            lines.append(f"- ... and {len(priority_files) - 50} more")
    lines.append("")

    # --- Solana scanner (Solana / Anchor / Rust targets only) ---
    rust_files = list(target.rglob("*.rs"))
    is_rust = bool(rust_files)
    is_solidity = any(target.rglob("*.sol"))

    if is_rust:
        from src.agents.solana_scanner import SolanaScanner
        scanner = SolanaScanner(target)
        all_results = scanner.all()

        lines.append("## Solana scanner — high-signal categories")
        lines.append("")
        lines.append(scanner.summary())
        lines.append("")

        # Surface specific high-signal hits with file:line
        cfg_if_hits = all_results.get("variant_asymmetry", [])
        if cfg_if_hits:
            lines.append(f"### cfg_if variant asymmetry ({len(cfg_if_hits)} hits)")
            lines.append("")
            lines.append("Safety check present in some feature-gated branches "
                         "but missing in others. **Highest-EV target type.**")
            lines.append("")
            for h in cfg_if_hits:
                lines.append(f"- `{h['file']}:{h['line']}` — {h['snippet']}")
            lines.append("")

        no_signer = [h for h in all_results.get("entrypoints", [])
                     if not h.get("extra", {}).get("has_signer_check")]
        if no_signer:
            lines.append(f"### Entrypoints without obvious signer check ({len(no_signer)})")
            lines.append("")
            for h in no_signer[:30]:
                lines.append(f"- `{h['file']}:{h['line']}` {h['snippet']}")
            lines.append("")

        unchecked_arith = all_results.get("unchecked_arithmetic", [])
        if unchecked_arith:
            lines.append(f"### Unchecked arithmetic ({len(unchecked_arith)})")
            lines.append("")
            for h in unchecked_arith[:30]:
                lines.append(f"- `{h['file']}:{h['line']}` {h['snippet']}")
            if len(unchecked_arith) > 30:
                lines.append(f"- ... and {len(unchecked_arith) - 30} more")
            lines.append("")

        init_if_needed = all_results.get("init_if_needed", [])
        if init_if_needed:
            lines.append(f"### init_if_needed usages ({len(init_if_needed)})")
            lines.append("")
            lines.append("Anchor anti-pattern; often paired with close-then-revive bugs.")
            lines.append("")
            for h in init_if_needed:
                lines.append(f"- `{h['file']}:{h['line']}` {h['snippet']}")
            lines.append("")

        realloc_hits = all_results.get("realloc", [])
        if realloc_hits:
            lines.append(f"### realloc usages ({len(realloc_hits)})")
            lines.append("")
            for h in realloc_hits:
                lines.append(f"- `{h['file']}:{h['line']}` {h['snippet']}")
            lines.append("")

    elif is_solidity:
        lines.append("## Solidity static analysis (Slither)")
        lines.append("")
        lines.append("Run `sentinel scan <target>` separately for Slither-based output.")
        lines.append("")

    # --- Path 3: small-file speed sort ---
    if is_rust:
        lines.append("## Source files sorted ascending (Path 3 small-file-speed)")
        lines.append("")
        lines.append("Read smallest files first: helpers, state, error definitions. "
                     "Often hide invariants and hot paths in compact form.")
        lines.append("")
        sized = []
        for p in rust_files:
            # Skip common excludes
            if any(part in p.parts for part in ("target", ".git", "node_modules", "vendor", "tests")):
                continue
            try:
                with p.open() as f:
                    n = sum(1 for _ in f)
                sized.append((n, p.relative_to(target)))
            except OSError:
                continue
        sized.sort()
        for n, rel in sized:
            lines.append(f"- {n:5d} LoC — `{rel}`")
        lines.append("")

    # --- Manual hunting starter prompts ---
    lines.append("## Manual hunting starter prompts")
    lines.append("")
    lines.append("Per the value-flow chain (Sentinel feedback rule):")
    lines.append("")
    lines.append("For each entrypoint and priority file:")
    lines.append("")
    lines.append("1. **Value** — what tokens/lamports flow in/out?")
    lines.append("2. **State** — what accounts get mutated, in what order?")
    lines.append("3. **Assumptions** — what invariants does the code assume but not enforce?")
    lines.append("4. **Edge cases** — zero amounts, max u64, frozen accounts, missing accounts, "
                 "first-caller-wins races")
    lines.append("5. **Exploit path** — concrete attacker steps to extract value or brick the contract")
    lines.append("")
    lines.append("Pair with a **Spec → Code divergence pass** — the docs claim X, "
                 "look for the line where the code does Y.")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"Wrote orientation report to: {out_path}")
    print(f"  {len(known_findings)} known findings to skip")
    print(f"  {len(priority_files)} priority files")
    if is_rust:
        all_static = sum(len(v) for v in all_results.values())
        print(f"  {all_static} static-analysis signals across {len(all_results)} categories")
    return 0


if __name__ == "__main__":
    sys.exit(main())
